version: "3"
services:
  social-app-template-backend:
    build: .
    ports:
      - "5005:5005"
    env_file:
      - .env.docker.dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    networks:
      - social-app-template-backend-service
    depends_on:
      - frequency
      - kubo_ipfs
      - content-publishing-service-api
      - content-publishing-service-worker
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - social-app-template-backend-service
    volumes:
      - redis_data:/data/redis
  frequency:
    image: frequencychain/standalone-node:latest
    platform: linux/amd64
    ports:
      - 9944:9944
    networks:
      - social-app-template-backend-service
    container_name: frequency
    volumes:
      - chainstorage:/data
  kubo_ipfs:
    image: ipfs/kubo:latest
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    networks:
      - social-app-template-backend-service
    volumes:
      - ipfs_data:/data/ipfs

  content-publishing-service-api:
    image: amplicalabs/content-publishing-service:api-0.0.2-rc5
    platform: linux/amd64
    ports:
      - 3001:3001
    env_file:
      - .env.docker.dev
    environment:
      - START_PROCESS=api
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
      - kubo_ipfs
    networks:
      - social-app-template-backend-service

  content-publishing-service-worker:
    image: amplicalabs/content-publishing-service:api-0.0.2-rc5
    platform: linux/amd64
    env_file:
      - .env.docker.dev
    environment:
      - START_PROCESS=worker
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
    depends_on:
      - redis
      - frequency
      - kubo_ipfs
    networks:
      - social-app-template-backend-service

volumes:
  ipfs_data:
  chainstorage:
    external: false
  redis_data:

networks:
  social-app-template-backend-service:
