# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Frontend Verify PR
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
defaults:
  run:
    working-directory: "./frontend"
jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
